import java.sql.*;
import Project.ConnectionProvider;
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import java.util.Formatter;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;




public class StudentRecord extends javax.swing.JFrame {

    /**
     * Creates new form StudentRecord
     */
    public StudentRecord() {
        initComponents();
         table_update();
        
    }
     public StudentRecord(String rollNo) {
        initComponents();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtsurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txtranking = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txthci = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtdba = new javax.swing.JTextField();
        txtdbms = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtdescrete = new javax.swing.JTextField();
        txtenglish = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtoop = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtadvanced = new javax.swing.JTextField();
        txtfinance = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnranking = new javax.swing.JButton();
        btntranscript = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Result System");
        setBackground(new java.awt.Color(0, 102, 51));

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "Student Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("RollNo:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("FirstName:");

        txtfirstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Course Code:");

        txtsurname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsurnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total Score:");

        txttotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        txtranking.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ranking:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("DBA");

        txthci.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txthci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthciKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Finance");

        txtdba.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdbaKeyTyped(evt);
            }
        });

        txtdbms.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdbms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdbmsKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("HCI");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Descrete:");

        txtdescrete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdescrete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdescreteKeyTyped(evt);
            }
        });

        txtenglish.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtenglish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtenglishKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("English:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("OOP");

        txtoop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtoop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtoopKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("SurName:");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C98345", "C98654", "C98754", "C98531" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("DBMS");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Advanced");

        txtadvanced.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtadvanced.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtadvancedKeyTyped(evt);
            }
        });

        txtfinance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtfinance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfinanceKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfirstname)
                                    .addComponent(jComboBox1, 0, 172, Short.MAX_VALUE)
                                    .addComponent(txtsurname, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jButton1))))
                            .addComponent(jSeparator1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttotal)
                            .addComponent(txtranking))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtadvanced, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14)
                            .addComponent(jLabel7))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfinance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(txthci, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtdba)
                            .addComponent(txtdbms)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtenglish)
                            .addComponent(txtdescrete)
                            .addComponent(txtoop))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtdescrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtenglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtoop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtadvanced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtdba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel9))
                            .addComponent(txthci, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfinance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtdbms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4), "Grade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jTextArea1.setBackground(new java.awt.Color(51, 102, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jTable1.setBackground(new java.awt.Color(51, 102, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RollNo", "FirstName", "Course_Code", "Descrete", "English", "OOP", "Advanced", "DBA", "HCI", "Finance", "DBMS", "Total_Score", "Ranking"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnranking.setBackground(new java.awt.Color(51, 102, 0));
        btnranking.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnranking.setText("Ranking");
        btnranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrankingActionPerformed(evt);
            }
        });

        btntranscript.setBackground(new java.awt.Color(51, 102, 0));
        btntranscript.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntranscript.setText("Transcript");
        btntranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntranscriptActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(51, 102, 0));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(51, 102, 0));
        btnreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(51, 102, 0));
        btndelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnexit.setBackground(new java.awt.Color(51, 102, 0));
        btnexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(51, 102, 0));
        btnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnranking)
                        .addGap(77, 77, 77)
                        .addComponent(btnsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(btntranscript)
                        .addGap(130, 130, 130)
                        .addComponent(btnupdate)
                        .addGap(149, 149, 149)
                        .addComponent(btndelete)
                        .addGap(143, 143, 143)
                        .addComponent(btnreset)
                        .addGap(127, 127, 127)
                        .addComponent(btnexit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnranking)
                    .addComponent(btndelete)
                    .addComponent(btnupdate)
                    .addComponent(btntranscript)
                    .addComponent(btnexit)
                    .addComponent(btnreset)
                    .addComponent(btnsave))
                .addGap(160, 160, 160))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     public void table_update(){
         int c;
         try{
            Connection con=ConnectionProvider.getCon();
           Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("select * from result "); 
           
           ResultSetMetaData rm= rs.getMetaData();
           c=rm.getColumnCount();
           DefaultTableModel dft=(DefaultTableModel) jTable1.getModel();
           dft.setRowCount(0);
           
           
           while(rs.next()){
               
               Vector v= new Vector();
               
               for(int i=1; i<=c;i++){
                   
                   v.add(rs.getString("Rollno"));
                   v.add(rs.getString("FirstName"));
                     v.add(rs.getString("Surname"));
                      v.add(rs.getString("Descrete"));
                       v.add(rs.getString("English"));
                        v.add(rs.getString("OOP"));
                         v.add(rs.getString("Advanced"));
                         v.add(rs.getString("DBA"));
                         v.add(rs.getString("HCI"));
                         v.add(rs.getString("Finance"));
                         v.add(rs.getString("dbms"));
                         v.add(rs.getString("Total_Score"));
                         v.add(rs.getString("Ranking"));
               }
               dft.addRow(v);
           }
         
         }
         catch(Exception e){
             
         }
    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
      
        setVisible(false);
        new StudentRecord().setVisible(true);

       
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
         int a=JOptionPane.showConfirmDialog(null,"Do you really want to exit?","Student Result System",JOptionPane.YES_NO_OPTION );
        if(a==0){
           System.exit(0);
                    }
    }//GEN-LAST:event_btnexitActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int a =JOptionPane.showConfirmDialog(null,"Do you really want  to delete","select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            String rollno=jTextField1.getText();
            try{
                Connection con=ConnectionProvider.getCon();
                Statement st= con.createStatement();
                st.executeUpdate("delete from result where RollNo='"+rollno+"'");
               JOptionPane.showMessageDialog(null, "successfylly Delete");
                setVisible(false);
            new StudentRecord().setVisible(true);
            
             }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
          
         
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnrankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrankingActionPerformed
        // TODO add your handling code here
       
        int s1 = Integer.parseInt(txtdescrete.getText());
        int s2 = Integer.parseInt(txtenglish.getText());
        int s3 = Integer.parseInt(txtoop.getText());
        int s4 = Integer.parseInt(txtadvanced.getText());
        int s5 = Integer.parseInt(txtdba.getText());
        int s6 = Integer.parseInt(txthci.getText());
        int s7 = Integer.parseInt(txtfinance.getText());
        int s8 = Integer.parseInt(txtdbms.getText());
        
         int total=(s1+s2+s3+s4+s5+s6+s7+s8)/8;
       
        
        String s=String.valueOf(total);
        
        txttotal.setText(s);
     
        
       
        if(total >= 70){
            txtranking.setText("EXCELLENT");
        }
        else if(total >= 60){
           txtranking.setText("VERY GOOD"); 
        }
         else if(total >= 50){
           txtranking.setText("GOOD"); 
        }
         else if(total >= 40){
           txtranking.setText("GOOD"); 
        }
         else if(total >= 30){
           txtranking.setText("FAIL"); 
        }
         else if(total >= 20){
           txtranking.setText("FAIL"); 
        }
        
       
     
           
    }//GEN-LAST:event_btnrankingActionPerformed

    private void txtsurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsurnameActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtdescreteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescreteKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtdescreteKeyTyped

    private void txtenglishKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtenglishKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtenglishKeyTyped

    private void txtoopKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoopKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtoopKeyTyped

    private void txtadvancedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadvancedKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtadvancedKeyTyped

    private void txtdbaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdbaKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtdbaKeyTyped

    private void txthciKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthciKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txthciKeyTyped

    private void txtfinanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfinanceKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtfinanceKeyTyped

    private void txtdbmsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdbmsKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtdbmsKeyTyped

    private void btntranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntranscriptActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btntranscriptActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        try{
         Connection con=ConnectionProvider.getCon();
         Statement st=con.createStatement();
         ResultSet rs= st.executeQuery("update result set Course_Code='"+jComboBox1.getSelectedItem()+"' ,OOP='"+txtoop.getText()+"',HCI='"+txthci.getText()+"' where RollNo= '"+jTextField1.getText()+"'");
         JOptionPane.showMessageDialog(null, "Good Job Record is Updated...");
            st.close();
            con.close();
            
        }
        catch (Exception ex)
     
 {
     JOptionPane.showMessageDialog(null,ex);
     
                  
     }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int checkrollno=0;
       String rollno=jTextField1.getText();
       try{
           Connection con=ConnectionProvider.getCon();
           Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("select * from result where RollNo='"+rollno+"'");
           while(rs.next())
           {
               checkrollno=1;
               jTextField1.setText(rs.getString(1));
               txtfirstname.setText(rs.getString(2));
               txtsurname.setText(rs.getString(3));
               jComboBox1.setSelectedItem(rs.getString(4));
               txtdescrete.setText(rs.getString(6));
               txtenglish.setText(rs.getString(7));
               txtoop.setText(rs.getString(8));
               txtadvanced.setText(rs.getString(9));
               txtdba.setText(rs.getString(10));
               txthci.setText(rs.getString(11));
               txtfinance.setText(rs.getString(12));
               txtdbms.setText(rs.getString(13));
               txttotal.setText(rs.getString(14));
               txtranking.setText(rs.getString(16));
           }
           if(checkrollno==0)
               JOptionPane.showMessageDialog(null, "Member ID does not Exist");
           
       }
       catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex);
       }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
        String rollno=jTextField1.getText();
            String firstname=txtfirstname.getText();
            String surname=txtsurname.getText();
            String course=(String)jComboBox1.getSelectedItem();
            String descrete=txtdescrete.getText();
            String english=txtenglish.getText();
            String oop=txtoop.getText();
            String advanced=txtadvanced.getText();
            String dba=txtdba.getText();
            String hci=txthci.getText();
            String finance=txtfinance.getText();
            String dbms=txtdbms.getText();
            String total=txttotal.getText();
            String ranking=txtranking.getText();
            
            
            try{
                Connection con=ConnectionProvider.getCon();
                PreparedStatement ps=con.prepareStatement("Insert into result values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                ps.setString(1, rollno);
                ps.setString(2, firstname);
                ps.setString(3, surname);
                ps.setString(4, course);
                ps.setString(5, descrete);
                ps.setString(6, english);
                ps.setString(7, oop);
                ps.setString(8, advanced);
                ps.setString(9, dba);
                ps.setString(10, hci);
                ps.setString(11, finance);
                ps.setString(12, dbms);
                ps.setString(13, total);
                ps.setString(14, ranking);
           
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Successful Saved");
                table_update();
                
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            
            }
            
            
            
            
    }                                       

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        try{
            int a=JOptionPane.showConfirmDialog(null,"Do you really want to delete","Delete System",JOptionPane.YES_NO_OPTION);
            Connection con=ConnectionProvider.getCon();
           Statement st=con.createStatement();
           st.executeUpdate("delete from employee where IdEmployee='"+jTextField1.getText()+"'");
            JOptionPane.showMessageDialog(null, "successfylly Delete");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
      
    }//GEN-LAST:event_btnsaveActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel df=(DefaultTableModel) jTable1.getModel();
        int selectIndex= jTable1.getSelectedRow();
        
           jTextField1.setText(df.getValueAt(selectIndex, 1).toString());
           txtfirstname.setText(df.getValueAt(selectIndex, 2).toString());
           txtsurname.setText(df.getValueAt(selectIndex, 3).toString());
           jComboBox1.setSelectedItem(df.getValueAt(selectIndex, 3).toString());
           txtdescrete.setText(df.getValueAt(selectIndex, 4).toString());
           txtenglish.setText (df.getValueAt(selectIndex, 5).toString());
           txtoop.setText(df.getValueAt(selectIndex, 6).toString());
           txtadvanced.setText(df.getValueAt(selectIndex, 6).toString());
           txtdba.setText(df.getValueAt(selectIndex, 6).toString());
           txthci.setText(df.getValueAt(selectIndex, 6).toString());
           txtfinance.setText(df.getValueAt(selectIndex, 6).toString());
           txtdbms.setText(df.getValueAt(selectIndex, 6).toString());
           txttotal.setText(df.getValueAt(selectIndex, 6).toString());
           txtranking.setText  (df.getValueAt(selectIndex, 0).toString());
                 
                     
                     
               
                       
                           
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnranking;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btntranscript;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtadvanced;
    private javax.swing.JTextField txtdba;
    private javax.swing.JTextField txtdbms;
    private javax.swing.JTextField txtdescrete;
    private javax.swing.JTextField txtenglish;
    private javax.swing.JTextField txtfinance;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txthci;
    private javax.swing.JTextField txtoop;
    private javax.swing.JTextField txtranking;
    private javax.swing.JTextField txtsurname;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
